print("Lets get to know each other, I am pia, your personal assistance.")
print("")
name = input("What is your name?")
age = input("How old are you?")
location = input("Where are you from?")
print("Hello "+name+" you are "+age+" years old and live in "+location)